### ISSUE TITLE
[error TS2612: Property '' will overwrite the base property in 

### ISSUE THREAD

**Issue by Sandeep-Malhotra** [cap-js/cds-typer#286] opened 2024-07-31 02:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Error
**error TS2612: Property 'ID' will overwrite the base property in '_cuidAspect<{ new (...args: any[]): _managedAspect<TBase>.managed; prototype: _managedAspect<any>.managed; readonly actions: Record<never, never>; } & TBase>.cuid & _managedAspect<TBase>.managed & object'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.**

Entity Definition in service file
```
 entity ShiftHeaders         as
        projection on db.ShiftHeader {
            *
        }
        excluding {
            createdAt,
            createdBy,
            modifiedAt,
            modifiedBy
        };
```

Entity defined in db file
```
entity ShiftHeader : cuid, managed {
    nextCursor     :      db.WorkForceCursor;
    updateSequence :      Composition[1, * ] of ShiftRecord
                              on updateSequence.updateSequenceId = ID;
    errors         : many db.WorkforceError;
    warnings       : many db.WorkForceWarning;

}
```

Type generated in index.ts

```
export function _ShiftHeaderAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class ShiftHeader extends _._cuidAspect(_._managedAspect(Base)) {
        ID?: string;
        nextCursor?: _stce_api.WorkForceCursor | null;
        updateSequence?: __.Composition.of.many<ShiftRecord_>;
        errors?: Array<_stce_api.WorkforceError>;
        warnings?: Array<_stce_api.WorkForceWarning>;
      static readonly actions: Record<never, never>
  };
}
```

### Expected Behavior

Types must be generated without error 

### Environment

```markdown
- **OS**:
- **Node**:
- **npm**:
- **cds-typer**: 
- **cds**:
```

**Comment by daogrady** [comment] 2024-07-31 05:14
Duplicate of https://github.com/cap-js/cds-typer/issues/274

**Closed by daogrady** 2024-07-31 05:14 UTC
Labels: bug, new
