### ISSUE TITLE
[BUG] [REGRESSION] TS2612 - Property 'ID' will overwrite the base property in '_cuidAspect<TBase> (v0.23.0)

### ISSUE THREAD

**Issue by geert-janklaps** [cap-js/cds-typer#274] opened 2024-07-16 11:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

As of release v0.23.0 generated types using cuidAspect produce TS2612 errors. (strict tsconfig)
This issue might be closely related to #273.
![image](https://github.com/user-attachments/assets/ce49f05b-130a-4115-82e9-bf40a794b10d)

The fix however is different, in the compilerOptions you need to disable useDefineForClassFields.

```json
{
  "ts-node": {
    "files": true
  },
  "compilerOptions": {
    "paths": {
      "#cds-models/*": [
        "./@cds-models/*"
      ]
    },
    "rootDir": "./",
    "target": "ESNext",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "sourceMap": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": false,
    "skipLibCheck": true,
    "useDefineForClassFields": false
  }
}
```

### Expected Behavior

The generated types not to produce errors in strict mode

### Environment

```markdown
@cap-js/asyncapi: 1.0.1
@cap-js/cds-typer: 0.23.0
@cap-js/openapi: 1.0.4
@cap-js/sqlite: 1.7.3
@sap/cds: 7.9.3
@sap/cds-common-content: 1.4.0
@sap/cds-compiler: 4.9.6
@sap/cds-dk: 7.9.5
@sap/cds-dk (global): 8.0.2
@sap/cds-fiori: 1.2.7
@sap/cds-foss: 5.0.1
@sap/cds-hana: 2.0.0
@sap/cds-mtxs: 1.18.2
@sap/eslint-plugin-cds: 2.7.0
Node.js: v20.14.0
```

**Comment by cpf-hse** [comment] 2024-07-24 07:09
Thank you @geert-janklaps for the mentioned fix.
Had the same issue:
_error TS2612: Property 'createdAt' will overwrite the base property in '_managedAspect<TBase>.managed & object'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration._

@cap-js/asyncapi: 1.0.2
@cap-js/cds-typer: 0.24.0
@cap-js/cds-types: 0.6.3
@cap-js/openapi: 1.0.4
@cap-js/postgres: 1.9.1
@cap-js/sqlite: 1.7.3
@sap/cds: 8.0.4
@sap/cds-compiler: 5.0.6
@sap/cds-dk (global): 8.0.3
@sap/cds-fiori: 1.2.7
@sap/cds-foss: 5.0.1
@sap/cds-mtxs: 2.0.3
@sap/eslint-plugin-cds: 3.0.4
Node.js: v20.15.1

**Comment by daogrady** [comment] 2024-07-25 06:31
Hi Geert-Jan,

thanks for reporting this issue!
I am unable to reproduce the issue with the information I have so far.

With the following _tsconfig.json_:
```json
{
"compilerOptions": {
  "paths": {
    "#cds-models/*": [
      "./@cds-models/*"
    ]
  },
  "rootDir": "./",
  "target": "ESNext",
  "module": "NodeNext",
  "moduleResolution": "NodeNext",
  "sourceMap": true,
  "esModuleInterop": true,
  "forceConsistentCasingInFileNames": true,
  "strict": true,
  "noImplicitOverride": false,
  "skipLibCheck": true,
  "useDefineForClassFields": true
}
}
```

and this minimal model:

```cds
using { cuid } from '@sap/cds/common';
namespace my.bookshop;

entity Book: cuid {
    key ID : Integer;
    title : String;
    author : String;
    stock : Integer;
    price : Decimal(9,2);
}
```

I am running `tsc` (5.5.4) in my project root and I do not see any errors and the transpiler emits .js files just fine.

Could you please expand your sample with a minimal model I can reproduce the issue with? Thanks!

Best,
Daniel

**Comment by cpf-hse** [comment] 2024-07-25 07:50
I can support here as well as I also had this issue.

Steps to reproduce
`cds init typerbug
cds add typescript
npm install
`

Now add the following schema.cds to your db folder
`
using {managed} from '@sap/cds/common';

namespace typer.bug;

entity ManagedEntity : managed {
    key id        : UUID;
        something : String(15);
}
`

Now create a service.cds in the srv folder
`using {typer.bug as service} from '../db/schema';

service ManagedService {
    entity ManagedEntity as projection on service.ManagedEntity;
}`

Run build
`cds-ts build`

Output
`
Error: @cds-models/ManagedService/index.ts(7,5): error TS2612: Property 'createdAt' will overwrite the base property in '_managedAspect<TBase>.managed & object'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
@cds-models/ManagedService/index.ts(11,5): error TS2612: Property 'createdBy' will overwrite the base property in '_managedAspect<TBase>.managed & object'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
@cds-models/ManagedService/index.ts(12,5): error TS2612: Property 'modifiedAt' will overwrite the base property in '_managedAspect<TBase>.managed & object'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
@cds-models/ManagedService/index.ts(16,5): error TS2612: Property 'modifiedBy' will overwrite the base property in '_managedAspect<TBase>.managed & object'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.`

**Comment by daogrady** [comment] 2024-07-25 08:06
Hi Christian,

thanks for adding the reproduction steps! I can now see the error and will look into it.

Best,
Daniel

**Comment by cpf-hse** [comment] 2024-07-29 11:53
Hi @daogrady ,
thank you for providing a potential fix.
How would I be able to test it 😓 😄 ?

**Comment by daogrady** [comment] 2024-07-29 11:56
Hi Christian,

sorry, I forgot to attach [the relevant wiki page](https://github.com/cap-js/cds-typer/wiki/Trying-Out-Prerelease-Versions).

Best,
Daniel

**Comment by cpf-hse** [comment] 2024-07-31 06:43
@daogrady I try to do it this week.

**Comment by daogrady** [comment] 2024-08-07 10:10
Hi Christian,

sorry to hear and hope you recover quickly! 😕 I have merged the fix in question for a related problem. So I will for now assume the problem is fixed (with the next release). If you notice the problem resurfacing, feel free to reopen this issue.

Best,
Daniel

**Closed** 2024-08-07 11:59 UTC
Labels: bug, new
