### ISSUE TITLE
[BUG] @singular for sap.common.CodeList not considered during type generation

### ISSUE THREAD

**Issue by softproviding-chiuaruc** [cap-js/cds-typer#240] opened 2024-05-17 06:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Within schema.cds there is the following CodeList defined:
[
![Schema](https://github.com/cap-js/cds-typer/assets/15617292/f970bd76-e0ea-44b9-9768-7d4d2c1edc3d)
](url)
After generating the types with cds.typer in the resulting index.ts file the following definition (erroneous) is created:
[
![error typer](https://github.com/cap-js/cds-typer/assets/15617292/505b98fb-a825-43c5-a519-2005044a1b3b)
](url)
This leads to errors when building the CAP application.

### Expected Behavior

The generated code should have __LabelingOrderStatu**s**Aspect_ insted and not __LabelingOrderStatuAspect_

### Environment

```markdown
- **OS**: Windows 11
- **Node**: 18.15.0
- **npm**: 9.5.0
- **cds-typer**: 0.20.2
- **cds**: 7.9.0
```

**Comment by daogrady** [comment] 2024-05-17 07:04
Duplicate of https://github.com/cap-js/cds-typer/issues/229

**Closed by daogrady** 2024-05-17 07:04 UTC
Labels: bug, new
