### ISSUE TITLE
[BUG] Scoped Definitions translated into Typescript Namespaces are generated at the wrong position

### ISSUE THREAD

**Issue by tsteckenborn** [cap-js/cds-typer#122] opened 2023-12-12 09:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

When defining an entity within a namespace, such as:
```cds
entity Name.Something {
key something: String;
}

entity Name.SomethingElse {
key something: String;
}

entity Name {
key something: String;
somethingElse: Association to Name.SomethingElse
}
```

The namespace is (atleast in my test) created on the top position of the file. Yet that results in TypeScript errors:
```
A namespace declaration cannot be located prior to a class or function with which it is merged.
Class 'Something' used before it's declaration.
```

### Expected Behavior

The generated types shouldn't have TypeScript errors.

### Environment

```markdown
- **OS**: MacOs
- **Node**: v20.10.0
- **npm**:
- **cds-typer**: 0.13.0
- **cds**: 7.4.2
```

**Comment by daogrady** [comment] 2023-12-12 09:51
Hi Tobias,

thanks for reporting this issue! Creating a file with the contents you added above and running cds-typer on it produces no error for me.
Looking at the screenshot you initially showed me it seems more like a naming issue, as the error message mentions "declaration merging". Do you maybe have a namespace and an entity with the same name in your actual model? 

Best,
Daniel

**Comment by tsteckenborn** [comment] 2023-12-12 09:55
Yeah, that's correct. Adapted the [sample](https://cap.cloud.sap/docs/cds/cdl#scoped-names).

**Comment by daogrady** [comment] 2023-12-12 10:08
Thank you for updating the model. Looking at the linked documentation, namespaces are supposed to be named in lowercase. When I apply this change to the updated model from above the issue is resolved. I renaming your namespace to `name` an option for you?

**Comment by tsteckenborn** [comment] 2023-12-12 10:22
Adapted the naming slightly, to lead more into the direction of Scoped Definitions which are right now translated into Namespaces in TypeScript and not mislead into CDS namespaces.

**Comment by daogrady** [comment] 2023-12-14 10:33
Hi Tobias,

this issue is addressed in https://github.com/cap-js/cds-typer/pull/124
Feel free to give it a whirl with your actual model before it is released.

Best,
Daniel

**Comment by tsteckenborn** [comment] 2023-12-19 16:58
Looks good to me

**Closed** 2023-12-19 17:15 UTC
Labels: bug
