### ISSUE TITLE
[QUESTION] How to access data from request object for Actions

### ISSUE THREAD

**Issue by thakrawielitzki** [cap-js/cds-typer#61] opened 2023-09-01 11:40 UTC
### Question

Hello,

I currently try to migrate from cds2types to cds-typer and ran into an issue and I'm not sure if it's wanted behaviour or a bug.
I try to develop an service with an action and some input data.

This is an demo CDS to illustrate the issue.

```cds
service TestService {
	action sayHello(request:HelloRequest) returns HelloResponse;

	type HelloRequest {
		greeterName:String;
		toName:String;
	}

	type HelloResponse {
		greetingMessage:String; 
	}
}
```

Executing cds-typer with `cds-typer "*" --outputDirectory @cds-models` produces

```ts
// This is an automatically generated file. Please do not change its contents manually!
export type HelloRequest = {
    greeterName?: string;
    toName?: string;
};
export type HelloResponse = {
    greetingMessage?: string;
};
// function
export declare const sayHello: (request: HelloRequest) => HelloResponse;
```

We implement the service like this in Typescript [according to the cds-typer documentation](https://cap.cloud.sap/docs/tools/cds-typer#actions)

```ts
import { HelloRequest, HelloResponse, sayHello } from "../@cds-models/TestService/index";
import cds from '@sap/cds';

export default class TestService extends cds.ApplicationService {

    init() {
        this.on(sayHello, (request) => {
            
            console.log(request.data); // outputs: { request: { greeterName: 'asd', toName: 'qwe' } }

            const greeter = request.data.greeterName; // is undefined, 
            // const greeter = request.data.request.greeterName; // is not allowed by typescript

            const toName = request.data.toName; // is undefined
            // const toName = request.data.request.toName ; // is not allowed by typescript

            return {
                greetingMessage : `${greeter} greets ${toName}`
            };
        });

        return super.init();
    }
}
```

This service returns `greetingMessage : "undefined greets undefined"`, because request.data contains the `request` node from the parameter list of the action. But request.data is of type `HelloRequest`.

cds2types solved that issue by providing additional types like in this case ActionSayHelloParams and ActionSayHelloReturn.
ActionSayHelloParams would look like this:

```ts
export interface ActionSayHelloParams {
    request: HelloRequest;
}
```

## Question
What are we doing wrong or is there something missing?

Edit:
Added versions:
>@cap-js/cds-typer: 0.7.0
>@sap/cds: 7.1.2
>@sap/cds-compiler: 4.1.2
>@sap/cds-dk: 7.1.1
>@sap/cds-dk (global): 7.0.2
>@sap/cds-fiori: 1.0.0
>@sap/cds-foss: 4.0.2
>@sap/cds-mtxs: 1.10.0
<@sap/eslint-plugin-cds: 2.6.3
>Node.js: v18.16.1
>cds-typer: 1.0.0

**Comment by daogrady** [comment] 2023-09-04 06:05
Hi Arne,

you are not missing anything. Inference of action parameters, especially when they are structured, is still a bit flimsy. We are tracking this issue and I will make sure to address it asap.
The correct way would be, as you had already found out:

```ts
request.data.request.greeterName
```

for the time being best I can offer you is an ugly cast, in case you are blocked by this issue:
```ts
import { Request } from "@sap/cds/apis/services";
...

this.on(sayHello, (request) => {
  const request_ = request as unknown as Omit<Request, "data"> & {data: {request: HelloRequest}}
  const greeter = request_.data.request.greeterName;  // works
}
```

Best,
Daniel

**Comment by thakrawielitzki** [comment] 2023-09-04 10:03
Thanks Daniel for the explaination.
Then for now this will be the way to go.

Regards,
Arne

**Comment by daogrady** [comment] 2023-09-20 04:22
Hi Arne,

this should be addressed in cds-typer 0.10.0 (upcoming) in tandem with the next release of `@sap/cds`. I am therefore closing this issue now. If you should find that the problem persists after upgrading to the latest release after both packages have released their next version, feel free to re-open this issue or open up a new one.

Best,
Daniel

**Closed by daogrady** 2023-09-20 04:22 UTC
Labels: question, keepalive

**Comment by dragolea** [comment] 2023-09-22 11:45
Hello Dao,
I am currently working on a TS project and saw this issue regarding Actions. I saw that CDS Typer 0.10.0 was just released a few days ago. 
I have the following 'Customer' generated class, which has a bound action `sendMail1` and also an unbound action `sendMail`

`CDS-Typer generated classes`
```ts
export function _CustomerAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class Customer extends Base {
        name?: string;
        description?: string;
        address?: __.Association.to<_dxfrontier_decorators.Address>;
        address_ID?: string;
    sendMail1: (request: HelloRequest) => HelloResponse = undefined as unknown as this['sendMail1']
  };
}
export class Customer extends _._cuidAspect(_._managedAspect(_CustomerAspect(__.Entity))) {static drafts: typeof Customer}
export class Customers extends Array<Customer> {static drafts: typeof Customer}

export declare const sendMail: (request: HelloRequest) => HelloResponse;
```
```bash
`package.json versions`
"@cap-js/cds-typer": "^0.10.0"
"@sap/cds": "^7.2.1",
```

This generated class does not have the static property `.actions` when using Customer.actions according to release 0.10.0
I can get them only when I instantiate the class like `new Customer().actions`

I quick workaround to make this generated class work was to change. 
    `sendMail1: (request: HelloRequest) => HelloResponse = undefined as unknown as this['sendMail1']`
TO
    `static sendMail1: (request: HelloRequest) => HelloResponse` and now I can say `Customer.sendMail1`

Thanks and let me know if you need further info, 
Daniel

**Comment by daogrady** [comment] 2023-09-22 13:11
Hi Daniel,

could you please provide the relevant part of your model so I can try to reproduce this issue? Also, please include the output of running `npx cds-typer --version` from your project's root.

Best,
Daniel

**Comment by dragolea** [comment] 2023-09-22 17:01
Hi Dao,
Everything is all right now, looks like npx was blocked somehow on version 0.9.0, now I have 0.10.0
```bash
npx cds-typer --version
0.10.0
```
Was the typing fixed in this newer version? Or do we still have to use the mentioned workaround below? 

```ts
const request_ = request as unknown as Omit<Request, "data"> & {data: {request: HelloRequest}}
```
Is there any better alternative? I've seen two new props __returns & __parameters, do we make use of these somehow? 

Best,
Daniel
