### ISSUE TITLE
[BUG] Error "Cannot read properties of undefined (reading 'target')"

### ISSUE THREAD

**Issue by hakimio** [cap-js/cds-typer#217] opened 2024-04-24 06:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Error when trying to generate types:
```
const target = element.target?.name ?? element.type?.ref?.join('.') ?? element.type
                               ^

TypeError: Cannot read properties of undefined (reading 'target')
    at Resolver.resolveAndRequire (C:\my-project\node_modules\@cap-js\cds-typer\lib\components\resolver.js:438:32)
    at #printOperation (C:\my-project\node_modules\@cap-js\cds-typer\lib\visitor.js:371:42)
    at Visitor.visitEntity (C:\my-project\node_modules\@cap-js\cds-typer\lib\visitor.js:446:33)
    at Visitor.visitDefinitions (C:\my-project\node_modules\@cap-js\cds-typer\lib\visitor.js:99:22)
    at new Visitor (C:\my-project\node_modules\@cap-js\cds-typer\lib\visitor.js:88:14)
    at compileFromCSN (C:\my-project\node_modules\@cap-js\cds-typer\lib\compile.js:56:23)
    at compileFromFile (C:\my-project\node_modules\@cap-js\cds-typer\lib\compile.js:69:12)

Node.js v20.11.0
```

### Expected Behavior

No error.

### Environment

```markdown
- **OS**: Windows 10
- **Node**: 20.11.0
- **npm**:
- **cds-typer**: 0.20.0
- **cds**: 7.8.2
```

### Anything else?

Might have been introduced in PR #196

**Comment by daogrady** [comment] 2024-04-24 06:56
Hi @hakimio ,

thanks for the report! I can not say for certain, as you have not attached a reproduction example, but this looks like it is the same as https://github.com/cap-js/cds-typer/issues/215 ?
If so, this has been addressed by the hotfix 0.20.1 I released earlier today.

Best,
Daniel

**Comment by hakimio** [comment] 2024-04-24 06:59
Hi Daniel,

I don't see the new version on [npm](https://www.npmjs.com/package/@cap-js/cds-types?activeTab=versions) or [the release page](https://github.com/cap-js/cds-typer/releases).

**Comment by hakimio** [comment] 2024-04-24 07:03
Also version number in the Changelog seems wrong: https://github.com/cap-js/cds-typer/blob/main/CHANGELOG.md#version-0211---2024-04-24

**Comment by daogrady** [comment] 2024-04-24 07:04
Hi Tomas,

true, the release has silently failed, probably because of the faulty entry you pointed out. Will fix in a minute, sorry for the inconvenience.

Best.
Daniel

**Comment by daogrady** [comment] 2024-04-24 07:11
0.20.1 is now available on npmjs, thanks for making me aware of the failed release. Let me know if this has fixed the issue you are encountering.

**Closed** 2024-04-24 07:14 UTC
Labels: bug, new
