### ISSUE TITLE
[BUG] [REGRESSION] Extra class properties with incorrect types added

### ISSUE THREAD

**Issue by hakimio** [cap-js/cds-typer#219] opened 2024-04-24 08:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Nature of Your Project

TypeScript

### Current Behavior

Let's say we have `User` entity defined the following way:
```ts
export class User extends _._cuidAspect(_._managedAspect(_UserAspect(__.Entity))) {}
```
The class already inherits `cuidAspect` and `managedAspect`.
`cuidAspect` defined as:
```ts
export function _cuidAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class cuid extends Base {
        ID?: string | null;
      static readonly actions: Record<never, never>
  };
}
```

Now, for whatever reason `cds-typer` decided to duplicate the inherited fields on the base class with **_different_** typing (`ID?: string` vs `ID?: string | null;`):
```ts
export function _UserAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class User extends Base {
        ID?: string;
        createdAt?: __.CdsTimestamp | null;
    /**
    * Canonical user ID
    */
        createdBy?: _.User | null;
        modifiedAt?: __.CdsTimestamp | null;
    /**
    * Canonical user ID
    */
        modifiedBy?: _.User | null;
          };
}
```

The duplicated fields appeared in the `service` class definitions but not in the `db schema` classes and because of this inconsistency I know get TS errors:
```
X [ERROR] NG2: Type 'import("models/gc/crm/index").User' is not assignable to type 'import("models/CrmService/index").User'.
  Types of property 'ID' are incompatible.
    Type 'string | null | undefined' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
```

### Expected Behavior

No TS errors after `cds-typer` update.

### Environment

```markdown
- **OS**: Windows 10
- **Node**: 20.11.0
- **npm**:
- **cds-typer**: 0.20.1
- **cds**: 7.8.2
```

### Anything else?

The last tested `cds-typer` version without the TS errors: `0.16.0`

**Comment by daogrady** [comment] 2024-04-24 08:06
Hi Tomas,

thanks for opening this issue, could you please attach the relevant part of your cds model for reproduction? Thanks!

Best,
Daniel

**Comment by hakimio** [comment] 2024-04-24 08:26
`schema.cds`
```cds
using {
    cuid,
    managed
} from '@sap/cds/common';

namespace gc.crm;

@assert.unique: {email: [email]}
entity Users : cuid, managed {
        name         : String not null  @mandatory;
        username     : String not null  @mandatory;
        isActive     : Boolean default true;
        status       : UserStatus default 'Available';
        phone        : String           @assert.format               : '^\+?[0-9 -]+$';
        email        : String not null  @assert.format               : '^[a-z-\.]+@([a-z-]+\.)+[a-z-]{2,4}$'  @mandatory;
        title        : Association to UserTitles;
}
```

`crm-service.cds`
```cds
using {gc.crm as crm} from 'schema';

service CrmService @(path: '/api') {
    entity Users              as projection on crm.Users;
    entity UserTitles         as projection on crm.UserTitles;
}
```

`index.cds`
```cds
using from 'crm-service';
```

**Comment by hakimio** [comment] 2024-04-24 08:38
`schema.cds`
```cds
using {
    cuid,
    managed
} from '@sap/cds/common';

namespace gc.crm;

@assert.unique: {email: [email]}
entity Users : cuid, managed {
        name         : String not null  @mandatory;
        username     : String not null  @mandatory;
        isActive     : Boolean default true;
        status       : UserStatus default 'Available';
        phone        : String           @assert.format               : '^\+?[0-9 -]+$';
        email        : String not null  @assert.format               : '^[a-z-\.]+@([a-z-]+\.)+[a-z-]{2,4}$'  @mandatory;
        title        : Association to UserTitles;
}

entity UserTitles : cuid, managed {
    name        : String not null @mandatory;
    description : String(500);
    isActive    : Boolean default true;
    users       : Association to many Users
                      on users.title = $self;
}
```

`crm-service.cds`
```cds
using {gc.crm as crm} from 'schema';

service CrmService @(path: '/api') {
    entity Users              as projection on crm.Users;
    entity UserTitles         as projection on crm.UserTitles;
}
```
`index.cds`
```cds
using from 'crm-service';
```

**Comment by daogrady** [comment] 2024-04-24 09:40
Thanks for adding the model! Your `Users.status` is referring to `UserStatus`, which is not included. Could you please add that as well?

**Comment by hakimio** [comment] 2024-04-24 09:43
Sure, but I don't think it changes anything:
`types.cds`
```cds
type UserStatus : String enum {
    Available;
    Busy;
    DoNotDisturb;
    Remote;
}
```

The problem is mismatching `ID` types in schema TS definitions and service TS definitions.

**Comment by daogrady** [comment] 2024-04-24 10:06
Thanks, I can now reproduce the issue. The minimal repro seems to be:

```cds
using { cuid } from '@sap/cds/common';

namespace ns;

entity A {
    x: Association to B;
}

entity B : cuid {}
```

and interestingly, when maintaining an `Association` to an entity that extends `cuid` (here: to `B`), the types for **`cuid`** change from 

```ts
export function _cuidAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class cuid extends Base {
        ID?: string | null;
      static readonly actions: Record<never, never>
  };
}
```

to

```ts
export function _cuidAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class cuid extends Base {
        ID?: string;
      static readonly actions: Record<never, never>
  };
}
```

which ultimately causes the mismatch between the two declarations of `ID`.
That should not happen. I will investigate and include this into the test suite.

**Comment by daogrady** [comment] 2024-04-25 14:11
The root cause here is actually the order in which the elements are handled. It is somehow strange that this occurs only now, but I have prepared a bandaid fix for this which passes the related tests.
@hakimio would you mind trying out [the related PR](https://github.com/cap-js/cds-typer/pull/226) on your actual model to confirm it resolves the problem for you?
(@siarhei-murkou fyi, since you originally contributed nullability)

**Comment by daogrady** [comment] 2024-04-26 14:08
I will look into this again next week then.

> Why have you decided to duplicate the properties anyway?

Since projections can contain `as`, as well as `excluding` expressions, it is much more straightforward to explicitly duplicate the entity we are projecting on with the properties that are explicitly given in the projection. As long as they turn out to be of identical type, this does not cause any issue since TS uses duck typing. The problem only arises once the types for some properties diverge, as seems to be the case here.

**Comment by tsteckenborn** [comment] 2024-04-29 07:50
I guess another quite minimal sample for this issue is:

```cds
service Test {
    entity test.TestEntity : managed {}
    entity TestEntity as projection on test.TestEntity;
}
```

Within the created TypScript files theres:
```ts
export function _temporalAspect<TBase extends new (...args: any[]) => object>(Base: TBase) {
  return class temporal extends Base {
        validFrom?: __.CdsTimestamp | null;
        validTo?: __.CdsTimestamp | null;
      static readonly actions: Record<never, never>
  };
}
```

With the CdsTimestamp reporting:
```
Namespace '"/Users/.../.../.../@cds-models/_/index"' has no exported member 'CdsTimestamp'.ts(2694)
```

**Comment by daogrady** [comment] 2024-04-30 15:46
Checking in on this again, could you please provide the code where you are using the types? Why are you attempting to assign a model entity to a variable of the type of the projection entity anyway?

**Comment by hakimio** [comment] 2024-04-30 17:44
I am only using service entities but those service entities are referring to model entities as their child entities/associations.
For example, the `User` entity defined in the service namespace is referring to `UserTitle` defined in the model:
```
title?: __.Association.to<_gc_crm.UserTitle> | null;
```
Now, if I import `UserTitle` from the service namespace, I can no longer assign the `user.title` property on the `User` entity which is also imported from the same service namespace.

**Comment by daogrady** [comment] 2024-05-06 07:22
I am unclear what you mean by "I can no longer assign the user.title property on the User entity"? What can you not assign to it?
I have whipped up a small sample of what sounds like what you are trying to do, but that seems to work on my end:

```ts
import { ApplicationService } from '@sap/cds'

export class MyService extends ApplicationService { async init() { super.init();
    const { User, UserTitle } = await import('#cds-models/CrmService')  // both imported from the service namespace
    const u = new User()
    u.title = new UserTitle()  // no type errors
}}
```

I have used the CDS snippets you provided above and cds-typer 0.20.2.

I am afraid I am currently doing a lot of reverse engineering/ amending of your model/ setup/ application. Could you possibly attach a _minimal, fully self contained_ example where I can observe the described behaviour, possibly in a repository? That would be highly appreciated!

**Comment by hakimio** [comment] 2024-05-07 12:53
Ok, simplified variant of the issue in the following screenshots:

`id1: string | undefined`

![id1](https://github.com/cap-js/cds-typer/assets/768105/e691a34d-85df-427b-88ef-e9bac304f26c)

`id2: string | undefined | null`

![id2](https://github.com/cap-js/cds-typer/assets/768105/60a5ebf1-6157-4d1e-8fe6-3eb9b380bbab)

`not assignable`

![not assignable](https://github.com/cap-js/cds-typer/assets/768105/fbfabd6d-75cf-426f-8c71-db465ded3975)

I have defined the `UserTitles` entity above. If you don't think that's an issue worth fixing, feel free to close this.

**Comment by hakimio** [comment] 2024-05-08 06:19
Hi @daogrady 

Here is what could be called "real-world" reproduction of the issue:

```ts
// Service imports
import type {Comment, User} from '@my-app/models/MyService';

const comment: Comment = {};
// TS error: types of property ID are incompatible
const user: User = comment.user!;
```

![image](https://github.com/cap-js/cds-typer/assets/768105/d70c2841-31dd-46f1-a44c-52bf5a56a6ad)

**Comment by siarhei-murkou** [comment] 2024-06-17 13:46
Hi @daogrady ,
I've pulled the changes from the PR locally, tried to compile CDS to TS and got the same issue that keys are compiled as nullable fields.

---

Hi @hakimio ,

FYI, I've already prepared some fixes in past, could you please pull [this branch](https://github.com/siarhei-murkou/cds-typer/tree/fix/nullable-refs) locally and check if it fixes your problem?

**Comment by daogrady** [comment] 2024-06-18 11:04
Hi @siarhei-murkou,

I can confirm that your fix resolves the issue on the minimal model; highly appreciated!

Let's wait a bit for Tomas to check it out on his actual model for added confidence, so I would merge the fix either after we hear back or at the latest at the end of the week.

Best,
Daniel

**Closed** 2024-06-20 12:42 UTC
Labels: bug, keepalive
